version: '3'
services:
  cache-demo:
    build: .
    #ports:
    #- "3333:3333"  
    environment:
    - SERVER_PORT=3333
    - SPRING_DATA_MONGODB_HOST=mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    hostname: mongo-server
